services:
  - type: web
    name: rio-backend-api
    runtime: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.hctvyazovhjyajqohmto:Harsh%40wardhan987@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - key: DATABASE_SYNC_URL
        value: postgresql://postgres.hctvyazovhjyajqohmto:Harsh%40wardhan987@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - key: SUPABASE_URL
        value: https://hctvyazovhjyajqohmto.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_VUGUEoOapv686UqbZ6joFw_-Uoq5IaB
      - key: RAZORPAY_KEY_ID
        value: rzp_test_1DP5mmOlF5G5ag
      - key: RAZORPAY_KEY_SECRET
        value: placeholder_secret
      - key: RAZORPAY_WEBHOOK_SECRET
        value: rio_whsec_test_live_sandbox_99
      - key: JWT_SECRET_KEY
        value: rio-fintech-jwt-secret-key-buildathon-2026
      - key: MODEL_DIR
        value: ../ml/models
